fix: dbapi raised AttributeError with [] as arguments
If the cursor.execute(sql, args) function was called with an empty array
instead of None, it would raise an AttributeError like this:

AttributeError: 'list' object has no attribute 'items'

This is for example automatically done by SQLAlchemy when executing a
raw statement on a dbapi connection.